name: Build CI

on:
  push:
    paths:
      - ".github/workflows/build-kpm.yml"
      - "**.c"

  workflow_dispatch:
    inputs:
      release:
        description: 'Push a new release'
        required: false
        default: 'false'
      version:
        description: 'release version'
        required: false
        default: '2024051900'

jobs:
  Build-on-Ubuntu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: UTC-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 1

      - name: Install Compiler
        run: |
          mkdir -p .tools
          curl -o .tools/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz \
            https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
          tar -C .tools -Jxf .tools/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz
          rm -f .tools/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf.tar.xz

      - name: Build kpm
        env:
          TARGET_COMPILE: ${{ github.workspace }}/.tools/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-
          ANDROID: "1"
        run: |
          mkdir -p target
          shopt -s nullglob
          for mk in */Makefile; do
            dir=$(dirname "$mk")
            make -C "$dir"
            for kpm in "$dir"/*.kpm; do
              [ -f "$kpm" ] || continue
              mv -v "$kpm" "target/$(basename "$kpm")"
            done
          done
          shopt -u nullglob

      - name: Upload artifact
        if: success()
        uses: lzghzr/upload-artifact@405e6269d5b1feb22bf2a044deb7950596bed6da
        with:
          path: "target/*.kpm"
          artifact-per-file: true
          artifact-name-rule: ${name}

      - name: Upload release
        if: github.event.inputs.release == 'true' && success() && !cancelled()
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.inputs.version }}
          tag: ${{ github.event.inputs.version }}
          body: This release is built by github-action.
          artifacts: "target/*.kpm"
          allowUpdates: true
          makeLatest: true
          omitBodyDuringUpdate: true
          replacesArtifacts: true